/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../../../core";

export type Response = core.APIResponse<
  MirrorworldApi.marketplaces.MintResponse,
  MirrorworldApi.marketplaces.mint.mintNft.Error
>;
export type Error =
  | MirrorworldApi.marketplaces.mint.mintNft.Error.BadRequest
  | MirrorworldApi.marketplaces.mint.mintNft.Error._Unknown;

export declare namespace Error {
  interface BadRequest extends _Utils {
    statusCode: 400;
  }

  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: MirrorworldApi.marketplaces.mint.mintNft.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    badRequest: () => _Result;
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  badRequest: (): MirrorworldApi.marketplaces.mint.mintNft.Error.BadRequest => {
    const valueWithoutVisit: Omit<MirrorworldApi.marketplaces.mint.mintNft.Error.BadRequest, "_visit"> = {
      statusCode: 400,
    };
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: MirrorworldApi.marketplaces.mint.mintNft.Error.BadRequest, visitor: MirrorworldApi.marketplaces.mint.mintNft.Error._Visitor<_Result>) {
      return MirrorworldApi.marketplaces.mint.mintNft.Error._visit(this, visitor);
    });
  },

  _unknown: (fetcherError: core.Fetcher.Error): MirrorworldApi.marketplaces.mint.mintNft.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<
      MirrorworldApi.marketplaces.mint.mintNft.Error._Unknown,
      "_visit"
    >;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: MirrorworldApi.marketplaces.mint.mintNft.Error._Unknown, visitor: MirrorworldApi.marketplaces.mint.mintNft.Error._Visitor<_Result>) {
      return MirrorworldApi.marketplaces.mint.mintNft.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: MirrorworldApi.marketplaces.mint.mintNft.Error,
    visitor: MirrorworldApi.marketplaces.mint.mintNft.Error._Visitor<_Result>
  ): _Result => {
    switch (value.statusCode) {
      case 400:
        return visitor.badRequest();
      default:
        return visitor._other(value as any);
    }
  },
} as const;
