/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../../../core";

export const MintResponse: core.schemas.ObjectSchema<
  serializers.marketplaces.MintResponse.Raw,
  MirrorworldApi.marketplaces.MintResponse
> = core.schemas.object({
  data: core.schemas.lazyObject(async () => (await import("../../../..")).marketplaces.MintResponseData),
});

export declare namespace MintResponse {
  interface Raw {
    data: serializers.marketplaces.MintResponseData.Raw;
  }
}
