/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";

export interface MintCollectionReq {
  name: string;
  symbol: string;
  url: string;
  confirmation: MirrorworldApi.marketplaces.Confirmation;
  sellerFeeBasisPoints: number;
}
