/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { Client as MintClient } from "../resources/mint/client/Client";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    apiKey?: core.Supplier<string>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  #mint: MintClient | undefined;

  public get mint(): MintClient {
    return (this.#mint ??= new MintClient(this.options));
  }
}
