/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../core";
import * as serializers from "../..";

export const ListNftRequest: core.schemas.ObjectSchema<ListNftRequest.Raw, MirrorworldApi.ListNftRequest> =
  core.schemas.object({
    mintAddress: core.schemas.property("mint_address", core.schemas.string()),
    price: core.schemas.number(),
    confirmation: core.schemas.lazy(async () => (await import("../..")).TransactionConfirmation),
  });

export declare namespace ListNftRequest {
  interface Raw {
    mint_address: string;
    price: number;
    confirmation: serializers.TransactionConfirmation.Raw;
  }
}
