/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../core";

export const ListNftData: core.schemas.ObjectSchema<ListNftData.Raw, MirrorworldApi.ListNftData> = core.schemas.object({
  tx: core.schemas.string(),
  feeEstimate: core.schemas.number(),
});

export declare namespace ListNftData {
  interface Raw {
    tx: string;
    feeEstimate: number;
  }
}
