/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../core";

export const ListNftStatus: core.schemas.Schema<ListNftStatus.Raw, MirrorworldApi.ListNftStatus> = core.schemas.enum_([
  "success",
  "fail",
]);

export declare namespace ListNftStatus {
  type Raw = "success" | "fail";
}
