/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../core";

export const TransactionConfirmation: core.schemas.Schema<
  TransactionConfirmation.Raw,
  MirrorworldApi.TransactionConfirmation
> = core.schemas.enum_(["finalized", "errored"]);

export declare namespace TransactionConfirmation {
  type Raw = "finalized" | "errored";
}
