/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { Client as TransactionApprovalClient } from "../resources/transactionApproval/client/Client";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    apiKey?: core.Supplier<string>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  #transactionApproval: TransactionApprovalClient | undefined;

  public get transactionApproval(): TransactionApprovalClient {
    return (this.#transactionApproval ??= new TransactionApprovalClient(this.options));
  }
}
