/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";

export interface ListNftRequest {
  mintAddress: string;
  price: number;
  confirmation: MirrorworldApi.TransactionConfirmation;
}
