/**
 * This file auto-generated by Fern from our API Definition.
 */

export type ListNftStatus = "success" | "fail";

export const ListNftStatus = {
  Success: "success",
  Fail: "fail",
} as const;
