/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";

export interface ListNftResponse {
  data: MirrorworldApi.ListNftData;
  code: number;
  error: string;
  status: MirrorworldApi.ListNftStatus;
}
