/**
 * This file auto-generated by Fern from our API Definition.
 */

export type TransactionConfirmation = "finalized" | "errored";

export const TransactionConfirmation = {
  Finalized: "finalized",
  Errored: "errored",
} as const;
