/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface AuthorizeRequest {
  clientId: string;
  redirectUri: string;
  responseType: string;
  grantType: string;
  state: string;
  email: string;
  password: string;
  scope: string;
}
