/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";

export interface BindPaymentCodeResponse {
  data: MirrorworldApi.authentication.BindPaymentCodeResponseData;
}
