/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../../../core";

export const Request: core.schemas.Schema<
  serializers.marketplaces.mint.mintNft.Request.Raw,
  MirrorworldApi.marketplaces.MintWithCollectionReq
> = core.schemas.object({
  collectionMint: core.schemas.property("collection_mint", core.schemas.string()),
  name: core.schemas.string(),
  symbol: core.schemas.string(),
  url: core.schemas.string(),
});

export declare namespace Request {
  interface Raw {
    collection_mint: string;
    name: string;
    symbol: string;
    url: string;
  }
}

export const Response: core.schemas.Schema<
  serializers.marketplaces.mint.mintNft.Response.Raw,
  MirrorworldApi.marketplaces.MintResponse
> = core.schemas.lazyObject(async () => (await import("../../../..")).marketplaces.MintResponse);

export declare namespace Response {
  type Raw = serializers.marketplaces.MintResponse.Raw;
}
