/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../../../core";

export const Request: core.schemas.Schema<
  serializers.marketplaces.mint.testEndpoint.Request.Raw,
  MirrorworldApi.marketplaces.TestRequest
> = core.schemas.object({
  myParameter: core.schemas.string(),
});

export declare namespace Request {
  interface Raw {
    myParameter: string;
  }
}
