/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../../../core";

export const Wallet: core.schemas.ObjectSchema<
  serializers.authentication.Wallet.Raw,
  MirrorworldApi.authentication.Wallet
> = core.schemas.object({
  ethAddress: core.schemas.property("eth_address", core.schemas.string()),
  solAddress: core.schemas.property("sol_address", core.schemas.string()),
});

export declare namespace Wallet {
  interface Raw {
    eth_address: string;
    sol_address: string;
  }
}
