/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../core";

export const AuthorizeRequest: core.schemas.ObjectSchema<AuthorizeRequest.Raw, MirrorworldApi.AuthorizeRequest> =
  core.schemas.object({
    clientId: core.schemas.property("client_id", core.schemas.string()),
    redirectUri: core.schemas.property("redirect_uri", core.schemas.string()),
    responseType: core.schemas.property("response_type", core.schemas.string()),
    grantType: core.schemas.property("grant_type", core.schemas.string()),
    state: core.schemas.string(),
    email: core.schemas.string(),
    password: core.schemas.string(),
    scope: core.schemas.string(),
  });

export declare namespace AuthorizeRequest {
  interface Raw {
    client_id: string;
    redirect_uri: string;
    response_type: string;
    grant_type: string;
    state: string;
    email: string;
    password: string;
    scope: string;
  }
}
