/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";
import * as core from "../../../core";

export const TokenRequest: core.schemas.ObjectSchema<TokenRequest.Raw, MirrorworldApi.TokenRequest> =
  core.schemas.object({
    code: core.schemas.string(),
    clientSecret: core.schemas.property("client_secret", core.schemas.string()),
    clientId: core.schemas.property("client_id", core.schemas.string()),
    grantType: core.schemas.property("grant_type", core.schemas.string()),
  });

export declare namespace TokenRequest {
  interface Raw {
    code: string;
    client_secret: string;
    client_id: string;
    grant_type: string;
  }
}
