/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MintResponseData {
  mintAddress: string;
  url: string;
  updateAuthority: string;
  creatorAddress: string;
  name: string;
  symbol: string;
  sellerFeeBasisPoints: number;
  collection?: string;
  signature: string;
  status: string;
}
