/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { MirrorworldApi } from "@fern-api/mirrorworld";

export interface MintResponse {
  data: MirrorworldApi.marketplaces.MintResponseData;
}
