/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as AuthenticationClient } from "./resources/authentication/client/Client";
import { Client as MarketplacesClient } from "./resources/marketplaces/client/Client";

export declare namespace MirrorworldApiClient {
  interface Options {
    environment?: environments.Environment | string;
    apiKey?: core.Supplier<string>;
  }
}

export class MirrorworldApiClient {
  constructor(private readonly options: MirrorworldApiClient.Options) {}

  #authentication: AuthenticationClient | undefined;

  public get authentication(): AuthenticationClient {
    return (this.#authentication ??= new AuthenticationClient(this.options));
  }

  #marketplaces: MarketplacesClient | undefined;

  public get marketplaces(): MarketplacesClient {
    return (this.#marketplaces ??= new MarketplacesClient(this.options));
  }
}
