/**
 * This file auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Production: "https://api.mirrorworld.fun/v1",
} as const;

export type Environment = typeof Environment.Production;
