/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Production: "https://api.mirrorworld.fun/",
} as const;

export type Environment = typeof Environment.Production;
